name: RPGPlugin
version: '1.0-SNAPSHOT'
main: github.eremiyuh.rPGPlugin.RPGPlugin
api-version: '1.21'
commands:
  selectclass:
    description: Opens a GUI to select your class
    usage: /<command>
    notes: "there are 3 classes, swordsman, archer, and alchemist.
    Swordsman have balanced atk and def,
    Archer have high attack output the farther the target is.
    Alchemist have high attack output but needs too much resources
    "
  status:
    description: Check information about your character
    usage: /<command>
  convertabysspoints:
    description: "Convert abyss points into 1 attribute point."
    usage: "/convertabysspoints"
  selectelement:
    description: "Select an elemental affinity."
    usage: "/<command> <fire|water|ice>"
    notes: "In pvp, fire > ice > water > fire, fire gets 10% final damage dealt, ice slows, water weakens"

  selectskill:
    description: Open the skill selection GUI
    usage: /selectskill
    notes: "every class has 3 skills, skill 1 focuses on elemental effects, skill 2 and skill 3 varies per class. Swordsman skill 2 will grant lifesteal, swordsman skill 3 will grant 
     great damage reduction.
     "
  teamcreate:
    description: "Creates a new team with your name."
    usage: "/teamcreate"
    notes: "It is recommended to raid abyss with a team. All members gain same exp as long you are about 40 blocks away from killed monster"
  teaminvite:
    description: Invite a player to your team.
    usage: /teaminvite <player>
    notes: "Every team can have up to 5 members"
  teamleave:
    description: Leave your current team.
    usage: /teamleave

  teaminviteaccept:
    description: Accept an invitation to join a team.
    usage: /teaminviteaccept <inviterName>
  teamremove:
    description: Remove player from a team.
    usage: /teamremove <playertoberemoved>
  pvpstatus:
    description: Set PVP on or off
    usage: /pvpstatus <onoroff>
  cc:
    description: short for chunk commands
    usage: /cc <claim|check>
    notes: "/cc claim will claim a whole chunk you are standing in. It will cost 1 claim point. /cc check will let you know claimed chunks near you, chunks surrounded
    by soul fire belongs to you, while chunks surrounded by fire belongs to others.
    "
  trust:
    description: claimed chunks trust command
    usage: /trust <playerName>
    notes: "lets people you trust to interact in the claimed chunk you are standing in"
  trustall:
    description: claimed chunks trust all command
    usage: /trustall <playerName>
    notes: "lets people you trust to interact in all your claimed chunks"
  untrust:
    description: claimed chunk untrust player command
    usage: /untrust <playerName>
  untrustall:
    description: claimed chunks untrust player to all chunks command
    usage: /untrustall <playerName>
  buyclaim:
    description: buy claim command
    usage: /buyclaim <claimpoint>
  convertmaterial:
    description: convert ores
    usage: /convert <orename>
    notes: "Converts some ores/ingot to a currency which can be seen on status gui"
  convertcurrency:
    description: convert currency
    usage: /convertcurrency <ore> <amount>
    notes: "Converts some ores/ingot currency which can be seen on status gui to a real material"
  warp:
    description: switch worlds
    usage: /warp a | ad | o
    notes: "For new players, it is recommended to have full netherite set with protection IV enchants before raiding the abyss.
    Fighting in abyss will cost the stamina and durability which can be seen through /status
    "
  giveap:
    description: "Gives attribute points to a player. Do not include on guide"
    usage: "/giveap <playername> <numberofpoints>"
    permission: RPGPlugin.giveap
    permission-default: op
  giveabysspoints:
    description: "Gives attribute points to a player. Do not include on guide"
    usage: "/giveabysspoints <playername> <numberofpoints>"
    permission: RPGPlugin.giveabysspoints
    permission-default: op
  fly:
    description: "flight."
    usage: "/fly"
    notes: "flying will cost 10 diamonds per minute"
  givesword:
    description: "givesword. Do not include on guide"
    usage: /<command>
    permission: RPGPlugin.givesword
    permission-default: op
  craftpotion:
    description: "use magic to convert your lapiz to potion"
    usage: /<command>
    notes: "this command is for alchemist, potion let's them throw a splash potion depending on their chosen skill.
    They will need a book on their offhand and right click on their mainhand to quickly craft a potion and throw it as they desire until they run out of potion.
    They can check that potion is a currency too in /status
    "
  rtp:
    description: "Randomly teleport to a location within the world borders."
    usage: "/rtp"
    note: "cost: 1 ender pearl"
  spawn:
    description: Teleports the player to the world spawn.
    usage: "/spawn"
    note: "cost: 1 ender pearl"
  sethome:
    description: Set player homes.
    usage: "/home <homeName>"
  home:
    description: Teleport to a saved home.
    usage: /home <homeName>
    note: "cost: 1 ender pearl"
  homedelete:
    description: Delete a saved home.
    usage: /homedelete <homeName>
  addstamina:
    description: Convert all food in your inventory to stamina.
    usage: /addstamina
  healthscale:
    description: Scales health to always show 10 hearts.
    usage: /healthscale
    note: "Provide more info or example scenario about how this work if you can"
  adddurability:
    description: Convert all ores in your inventory to durability.
    usage: /adddurability
    note: "
    Inform players about the rates:
    
        oresMap.put(Material.IRON_INGOT, 100);
        oresMap.put(Material.GOLD_INGOT, 200);
        oresMap.put(Material.EMERALD, 200);
        oresMap.put(Material.DIAMOND, 1000);
    "
  tphb:
    description: If you are stuck underground, use this command to teleport nearby highest block.
    usage: /tphb
    note: "cost: 1 ender pearl. Explain that this is only 5 distance x z and teleports them on highest solid block found"
  tpt:
    description: "Teleport To. Request to teleport to another player."
    usage: /tpt <playerName>
    note: "cost: 1 ender pearl when teleported"
  tpa:
    description: "Teleport Accept. Accept a pending teleport request from another player."
    usage: /tpa <playerName>
  register:
    description: "Register your account by setting up a password"
    usage: /register <password> <password>
  login:
    description: "Login using your password"
    usage: /login <password>
  sdw:
    description: Toggles the warning for stamina and durability.
    usage: /sdw
  rest:
    description: Simulate resting or sleep so won't be visited by phantoms.
    usage: /rest
  sv:
    description: admin summon villager.
    usage: /sv
    permission: RPGPlugin.villagerSetProf
    permission-default: op
  ascendtoggle:
    description: Toggle ascension of equips on or off.
    usage: /ascendtoggle
    notes: "Drag and drop same equip type and stat to ascend equip. The dragged equip will be lost after, 30% chance increase
    target equip stat per stat on the dragged equip.
    "
  villagerSetProf:
    description: Sets a villager's profession by custom name.
    usage: /villagerSetProf <villager customName> <profession>
    permission: RPGPlugin.villagerSetProf
    permission-default: op
  changepassword:
    description: "Admin command to change a player's password."
    usage: "/changepassword <playername> <newpassword>"
    permission: RPGPlugin.changepass
    permission-default: op
  tm:
    description: Initiate a trade with another player
    usage: /tm <playername> <offeredmaterialname> <amount> <wantedmaterialname> <amount>
  ta:
    description: Accept or reject a trade offer
    usage: /ta <playername>
  iteminfo:
    description: Checks the item name of the item you are holding
  grt:
    description: give reset token to player
    permission: RPGPlugin.changepass
    permission-default: op
  vault:
    description: Opens a vault for the player.
    usage: /vault <number>
    notes: "Currently offer 5 vaults"
  enderchest:
    description: Opens ender chest.
    usage: /enderchest
  abyssstore:
    description: Opens abyss store.
    usage: /abyssstore
    notes: "Gain abyss points by going to abyss world - /warp abyss"
  addstat:
    description: Add attributes.
    usage: /addstat attributename amount
  shopsavetploc:
    description: saves current location to let players tp to your shop
    usage: shopsavetploc
  tpshop:
    description: Teleports to a saved shop location of a player.
    usage: /<command> <playerName>
  pay:
    description: Pay another player a specified amount of currency.
    usage: /pay <playername> <currencyname> <amount>
  rwseed:
    description: Shows the seed of resource worlds.
    usage: /rwseed
  discordlink:
    description: Provides the link to the Discord server.
    usage: /discordlink
  junk:
    description: Opens a junk inventory for disposing of items.
  junkshop:
    description: Opens junk shop.
  tradinghall:
    description: Teleports the player to the trading hall.
    usage: /tradinghall
  showprofile:
    description: Toggle profile visibility to other players.
    usage: /showprofile
  buyhomeslot:
    description: buy /sethome slots
    usage: /buyhomeslot <number>
  tpallow:
    description: Allows a player to add others to their TP allow list.
    usage: /tpallow <playerName>
  tptoggle:
    description: Manage teleportation allow list.
    usage: /tptoggle <list> Or <remove <playername>>
    subcommands:
      list:
        description: Lists players allowed to teleport to you.
      remove:
        description: Removes a player from your teleport allow list.
  cosmeticstore:
    description: Allows a player buy cosmetics.
    usage: /command
  rename:
    description: Allows a player rename an item with colors.
    usage: /command
  showitem:
    description: "Announce your held item in chat."
  showitemgui:
    description: "Internal command to show GUI for a player's item."
  cestore:
    description: "Opens custom enchants store"
  fishsell:
    description: "Opens an inventory to convert fish into activity points"
  passiveskills:
    description: "Opens passive skills gui"
softdepend:
  - DiscordSRV