name: RPGPlugin
version: '1.0-SNAPSHOT'
main: github.eremiyuh.rPGPlugin.RPGPlugin
api-version: '1.21'
commands:
  selectclass:
    description: Opens a GUI to select your class
    usage: /<command>
  checkstatus:
    description: Check your current class
    usage: /<command>
  convertlevels:
    description: "Convert 100 experience levels into 1 attribute point."
    usage: "/convertlevels"
  selectelement:
    description: "Select an elemental affinity."
    usage: "/<command> <fire|water|ice>"
  selectrace:
    description: "Join race."
    usage: "/<command> <human|elf|orc|vampire|dwarf|demon|angel|darkelf>"
  selectskill:
    description: Open the skill selection GUI
    usage: /selectskill
  teamcreate:
    description: "Creates a new team with your name."
    usage: "/teamcreate"
  teaminvite:
    description: Invite a player to your team.
    usage: /teaminvite <player>

  teamleave:
    description: Leave your current team.
    usage: /teamleave

  teaminviteaccept:
    description: Accept an invitation to join a team.
    usage: /teaminviteaccept <inviterName>
  teamremove:
    description: Remove player from a team.
    usage: /teamremove <playertoberemoved>
  pvpstatus:
    description: Set PVP on or off
    usage: /pvpstatus <onoroff>
  cc:
    description: claimed chunks commands
    usage: /cc <claim|check>
  trust:
    description: claimed chunks trust command
    usage: /trust <playerName>
  trustall:
    description: claimed chunks trust all command
    usage: /trustall <playerName>
  untrust:
    description: claimed chunks untrust command
    usage: /untrust <playerName>
  untrustall:
    description: claimed chunks untrust all command
    usage: /untrustall <playerName>
  buyclaim:
    description: buy claim command
    usage: /buyclaim <claimpoint>
  convert:
    description: convert ores
    usage: /convert <orename>
  convertcurrency:
    description: convert currency
    usage: /convertcurrency <ore> <amount>
  switchworld:
    description: go to rpg world
    usage: /switchworld rpgworld
  giveap:
    description: "Gives attribute points to a player."
    usage: "/giveap <playername> <numberofpoints>"
  fly:
    description: "flight."
    usage: "/fly"
  givesword:
    description: "givesword"
    usage: /<command>
  buypotion:
    description: "use magic to convert your lapiz to potion"
    usage: /<command>
  rtp:
    description: "Randomly teleport to a location within the world borders."
    usage: "/rtp"
  spawn:
    description: Teleports the player to the world spawn.
    usage: "/spawn"
  sethome:
    description: Set player homes.
    usage: "/home <homeName>"
  home:
    description: Teleport to a saved home.
    usage: /home <homeName>
  homedelete:
    description: Delete a saved home.
    usage: /homedelete <homeName>