name: RPGPlugin
version: '1.0-SNAPSHOT'
main: github.eremiyuh.rPGPlugin.RPGPlugin
api-version: '1.21'
commands:
  selectclass:
    description: Opens a GUI to select your class
    usage: /<command>
  checkstatus:
    description: Check your current class
    usage: /<command>
  convertlevels:
    description: "Convert 100 experience levels into 1 attribute point."
    usage: "/convertlevels"
  selectelement:
    description: "Select an elemental affinity."
    usage: "/<command> <fire|water|earth|wind|lightning|ice>"
  selectrace:
    description: "Join race."
    usage: "/<command> <human|elf|orc|vampire|dwarf|demon|angel|darkelf>"
  selectskill:
    description: Open the skill selection GUI
    usage: /selectskill
  teamcreate:
    description: "Creates a new team with your name."
    usage: "/teamcreate"
  teaminvite:
    description: Invite a player to your team.
    usage: /teaminvite <player>
    permission: rpgplugin.teaminvite
  teamleave:
    description: Leave your current team.
    usage: /teamleave
    permission: rpgplugin.teamleave
  teaminviteaccept:
    description: Accept an invitation to join a team.
    usage: /teaminviteaccept <inviterName>
  teamremove:
    description: Remove player from a team.
    usage: /teamremove <playertoberemoved>
  pvpstatus:
    description: Set PVP on or off
    usage: /pvpstatus <onoroff>
